### ISSUE TITLE
Built engines are placed in the "output" folder

### ISSUE THREAD

**Issue by aikitoria** [comfyanonymous/ComfyUI_TensorRT#13]
Shouldn't they go in the "models" folder instead?

**Comment by comfyanonymous** [comment]
The reasoning is that the model directory can be read only or multiple folders while the output directory will always be a single directory that ComfyUI can write in.

It shouldn't matter that much because it will list engines from the output/tensorrt directory if you refresh the page or press the "Refresh" button.

**Comment by aikitoria** [comment]
I see, that makes sense.

**Comment by toyxyz** [comment]
If I change the output path using --output-directory, the generated files are not added to the list. I have to manually move them to the default output path(comfyui/outpu) to make them available.

**Comment by FatGuy84** [comment]
@comfyanonymous
Is there a way to change the path for loading the engines? My output folder is on a NAS, which affects performance when loading >5GB of data.
